import ProfileLight from "@/public/profile/light.svg"
import ProfileDark from "@/public/profile/dark.svg"
import AdminLight from "@/public/profile/admin_light.svg"
import AdminDark from "@/public/profile/admin_dark.svg"
import Department from "@/public/dep.svg"
import React, { useEffect,useState } from 'react'
import Link from '@/components/Link'
import Head from 'next/head'

const Home = () => {
    const [user, setUser] = useState((typeof window !== 'undefined' && localStorage.getItem('user').length > 0) ? JSON.parse(localStorage.getItem('user')) : "");
    const [theme, setTheme] = useState("dark");
    const [officeRole, setOfficeRole] = useState("-");
    const getOfficeOrRole = () =>{
        if (user) {
            setTheme(localStorage.getItem('theme'));
            setOfficeRole(user?.office ? user.office : user.role);
        }
    };
    useEffect(() => {
      if (typeof window !== 'undefined') {
        getOfficeOrRole();
      }
    },[])
    setInterval(() => {
        if (typeof window !== 'undefined') {
            setTheme(localStorage.getItem('theme'));
        }

    }, 10)
    return (<>
        <Head>
            <title>TKS - Homepage</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="flex items-center row-span-2  col-span-2 ... self-center mt-[4.5em] transform-gpu">
            <div className="ml-[3em] flex justify-between  w-[94%] h-[8em] rounded bg-gray-300  dark:bg-sky-900">
                <div className="flex ml-9 w-fit">
                    <div className="flex items-center transition-all duration-1000 ease-out">
                        {
                            theme === 'dark' ? (
                                user.role === 'admin' ?
                                <AdminDark/> : <ProfileDark/>
                            ) : (
                                user.role === 'admin' ?
                                <AdminLight/> : <ProfileLight/>
                            )
                        }
                    </div>
                    <div className="mt-7 mb-4 pr-7 ml-6 border-r-2 border-slate-900 dark:border-sky-300">
                        <h1 className="text-xl">{user ? user.name : "-"}</h1>
                        <h3 className="text-md text-zinc-400">{officeRole.charAt(0).toUpperCase() + officeRole.slice(1)}</h3>
                        <Link href="/profile">Acessar Perfil</Link>
                    </div>
                </div>

                <div className="flex w-fit">
                    <div className="flex ml-5 items-center transition-all duration-1000 ease-out">
                       <Department/>
                    </div>
                    <div className="mt-[2.2em] mb-4 pr-7 ml-2">
                        <h1 className="text-xl">Department: ABC 123</h1>
                        <h3 className="text-md text-zinc-400">Sector: ABC 123</h3>
                    </div>
                </div>
                {
                    user.role === 'employee' ?
                    (
                        <div className="flex w-fit">
                            <div className="flex ml-5 items-center transition-all duration-1000 ease-out">
                                {
                                    theme === 'dark' ? (
                                        user.role === 'admin' ?
                                        <AdminDark/> : <ProfileDark/>
                                    ) : (
                                        user.role === 'admin' ?
                                        <AdminLight/> : <ProfileLight/>
                                    )
                                }
                            </div>
                            <div className="mt-7 mb-4 pr-7 ml-2">
                                <h1 className="text-xl">{user ? user.name : "-"}</h1>
                                <h3 className="text-md text-zinc-400">{officeRole.charAt(0).toUpperCase() + officeRole.slice(1)}</h3>
                                <Link href="/profile">Acessar Perfil</Link>
                            </div>
                        </div>
                    ) : ''
                }   
            </div>
        </div>
    </>)
}


export default Home;