import Image from 'next/image';
import MainLight from "@/public/main/light.gif";
import MainDark from "@/public/main/dark.gif";
import ThemeSwitch from '@/components/ThemeSwitch'
import React, { useState } from 'react'
import Head from 'next/head'
const Login = () => {
    const [theme, setTheme] = useState("dark");
    setInterval(() => {
        if (typeof window !== 'undefined') {
            setTheme(localStorage.getItem('theme'));
        }

    })
    return (<>
       <Head>
            <title>TKS - Update Password</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='flex  flex-col w-[115vw] transition-all 1000s ease-in-out  self-center items-center justify-center transform-gpu'>
            {
                theme == 'light' ?  <Image src={MainLight} alt="" width={400} height={400}/>
                : <Image src={MainDark} alt="" width={400} height={400}/>
            }
            <div className='absolute top-3 right-0'>
                <ThemeSwitch />
            </div>       
            <h1 className='text-7xl font-extrabold'>Welcome back!</h1>
            <h3 className="text-3xl mt-5 text-zinc-400">We are happy to see you 🧭</h3>
        </div>
    </>)
}

export default Login;